version: "3.9"
services:
  simple-html:
    platform: linux/x86_64
    build: .
    image: simple-html:dev
    container_name: simple-html-container
    volumes:
      - ./:/app
    ports:
      - 7777:80
    restart: always